version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinema_db
    volumes:
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  app:
    image: tomcat:9.0.8-jre8
    volumes:
      - ./target/Cinema.war:/usr/local/tomcat/webapps/Cinema.war
#      - ./docker/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
#      - ./docker/server.xml:/usr/local/tomcat/conf/server.xml
    ports:
      - 8080:8080
    depends_on:
      - db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: cinema_db
