version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinema_db
    volumes:
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  app:
    build: ./docker
    volumes:
      - ./target/Cinema.war:/usr/local/tomcat/webapps/Cinema.war
      - ./docker/server.xml:/usr/local/tomcat/conf/server.xml
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      MY_SERVER_ADDRESS: db